### ISSUE TITLE
generated artifact from `build` doesn't work

### ISSUE THREAD

**Issue by storopoli** [poweranalyses-org/poweranalyses#15]
I don't know why but the generated artifact from the build job of `ci.yml` outputs a broken webpage.
The problem is in the `pa.js`

Try it yourself:

1. grab the artifact from the latest main PR.
2. open live-server in the extract dir.
3. check that the menus are broken.
4. now compile your own thing locally with `./scripts/build.sh`.
5. copy the fresh `pa.js` to the artifact extracted dir, i.e. `cp public/pa.js ~/Downloads/artifact/pa.js` (you might need to fix the `444` permissions).
6. redo step 2 of the live-server.
7. check that the menus and everything works.

I don't know how to fix this... 😢

**Comment by rikhuijzer** [comment]
Fixed in https://github.com/poweranalyses-org/poweranalyses/commit/92804f1b8a4b6ebe1d90353b03c09eff9d5e4d01.
